create table record (
  id bigint generated by default as identity,
  amount varchar(255),
  balance varchar(255),
  category varchar(255),
  date timestamp,
  revenue_or_expense varchar(255),
  summary varchar(255), primary key (id)
);
